### ISSUE TITLE
Not playing on Chrome 46

### ISSUE THREAD

**Issue by ddennis** [Jam3/web-audio-player#1]
Hi 

I am trying to implement this in an Angular project.
It plays fine on IOS 8.4.1 and 8.1.3, but I can't get it to play in Chrome version 46.0.2490.86 .

Further more i can only get it working on mobile by setting the buffer to false.
I have created a gist  to show my implementation, which is copy/Paste from your demo/index.js.

gist here: https://gist.github.com/ddennis/dfba77cfc052c52ec6ef

The demo link works fine on both mobil and in Chrome.

I have also tried the simple:

```
var createPlayer = require('web-audio-player')
var audio = audioPlayer('./sound/cheer.mp3')
    audio.on('load', function() {
   console.log('Audio loaded...')
   this.play()
})
```

The only thing i got workin was var the 'simple-media-element'

```
audioElement = media.audio('./sound/cheer.mp3', {
    loop: false,
    crossOrigin: 'Anonymous',
    volume: 0.5
    })
}
audioElement.play()
```

Any help would be much apprciated,

/Dennis

**Comment by mattdesl** [comment]
Hey @ddennis, in WebAudio land you have to connect your node to a destination in order to hear it. I'll update the example so that others don't fall into the same trap! :smile:

```
audioPlayer.play()
audioPlayer.node.connect(audioPlayer.context.destination)
```

**Comment by ddennis** [comment]
Thank you - i'll give it a try.
