### ISSUE TITLE
Any way to detect `file not found` error?

### ISSUE THREAD

**Issue by dy** [Jam3/web-audio-player#10]
As far web-audio-player is smart enough to recognize urls, I guess it would be very handy to inform user if the file is not found.
Some [reference](http://stackoverflow.com/questions/23231404/detecting-html5-audio-element-file-not-found-error)

**Comment by mattdesl** [comment]
Hmm, this should report as an error event. If not, we can patch the API to fix things.

``` js
var player = createPlayer('file.mp3').on('error', handleError);
player.play();
```

**Comment by dy** [comment]
It does not. 'xhr' returns 403 status, it does not generate error. That might be the reason I guess.

**Comment by mattdesl** [comment]
Ok, I'll take a closer look. :smile:

**Comment by mattdesl** [comment]
Can you provide a test case? It looks like xhr errors with `buffer: true` option should already emit `error` event on the player.

I also just published some changes that fix error handling for `buffer: false` (MediaElementSource) on Chrome/FF. Safari is a bit buggy for multiple sources, will have to revisit that. But now it should emit errors when the source 404s or isn't able to load.

**Comment by dy** [comment]
I faced that [here](https://github.com/dfcreative/start-app/blob/master/index.js#L780), when pointed src to `./file.mp3` which did not exist in served directory.

``` js
const createPlayer = require('web-audio-player');
let src = './file.mp3';
xhr({
    uri: src
}, (err, resp) => {
    if (err) return showError(err);
    if (resp.statusCode !== 200) return showError(src + ' not found');
    player.stop();
    player = createPlayer(src, {
        context: audioContext,
        buffer: isMobile, //← guess it is false
        crossOrigin: 'Anonymous'
    }).on('load', () => {
        player.play();
    }).on('error', (err) => {
        showError(err);
    });
});
```

Now I do `xhr` call to check the status if the file exists, but if I call `createPlayer(src, ...)` directly, it does not trigger any error if file not found. I suppose that is because under the hood `<audio>` element should include it’s source not as `src` attribute, but as `<source>` element.

**Comment by mattdesl** [comment]
`<audio>` element only exists if `buffer: false`, and it's already using `<source>` elements.

Can you test the following with the latest version (1.2.0).

``` js
var createPlayer = require('web-audio-player')

var shouldBuffer = false // can be true or false
var player = createPlayer('file.mp3', {
  buffer: shouldBuffer
}).on('error', function (err) {
  console.error('Got error:', err.message)
}).on('load', function () {
  console.log('Got load.')
})
```

It should log when there is an error or when it loads successfully. If for some reason an event isn't getting called, let me know what browser/device and I'll try to reproduce. :smile:

**Comment by dy** [comment]
It works, thanks @mattdesl :smile: !

**Comment by mattdesl** [comment]
Sweet!
